name: Docker Push ARM & Other

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"

jobs:
  
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2
        with: 
          ref: master
      - name: Print latest Commit
        run: git rev-parse master

      - id: should_run
        continue-on-error: true
        name: Check latest Commit is less than a week
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list --after="1 week"  master) && echo "::set-output name=should_run::false"

  push:
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    timeout-minutes: 720
    
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: curl -o Dockerfile https://raw.githubusercontent.com/dfuchss/synapse-arm/deploy/Dockerfile

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Log into Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build and Push
        uses: docker/build-push-action@v2
        timeout-minutes: 720
        with:
          context: .
          file: Dockerfile
          platforms: linux/arm/v7,linux/arm64
          push: true
          tags: "ghcr.io/${{ github.repository_owner }}/synapse:latest"

